# Generated by Django 4.0.4 on 2022-05-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteScanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='image',
            name='action',
            field=models.CharField(choices=[('uploadText', 'Upload as Text'), ('uploadFile', 'Upload as File'), ('translate', 'Translate Text'), ('uploadTranslate', 'Upload Translated Text'), ('readText', 'Read Text Out Loud'), ('readTextUpload', 'Read Text Out Loud and Then Upload Recording'), ('readTranslation', 'Read Translation Out Loud'), ('readTranslationUpload', 'Read Translation Out Loud and Then Upload Recording')], default='uploadFile', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='main_Img',
            field=models.ImageField(default=0, upload_to='static/noteScanner/input/'),
            preserve_default=False,
        ),
    ]
