# -*- coding: utf-8 -*-
"""
Created on Sat May 14 07:34:31 2022

@author: hgadd
"""

import difflib

languageShortNames = {'aa':'Afar','ab':'Abkhazian','af':'Afrikaans','ak':'Akan','sq':'Albanian','am':'Amharic','ar':'Arabic',
'an':'Aragonese','hy':'Armenian','as':'Assamese','av':'Avaric','ae':'Avestan','ay':'Aymara','az':'Azerbaijani','ba':'Bashkir',
'bm':'Bambara','eu':'Basque','be':'Belarusian','bn':'Bengali','bh':'Bihari languages','bi':'Bislama','bo':'Tibetan','bs':'Bosnian',
'br':'Breton','bg':'Bulgarian','my':'Burmese','ca':'Catalan; Valencian','cs':'Czech','ch':'Chamorro','ce':'Chechen','zh':'Chinese',
'cu':'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','cv':'Chuvash','kw':'Cornish','co':'Corsican',
'cr':'Cree','cy':'Welsh','cs':'Czech','da':'Danish','de':'German','dv':'Divehi; Dhivehi; Maldivian','nl':'Dutch; Flemish','dz':'Dzongkha',
'el':'Greek-Modern (1453-)','en':'English','eo':'Esperanto','et':'Estonian','eu':'Basque','ee':'Ewe','fo':'Faroese','fa':'Persian',
'fj':'Fijian','fi':'Finnish','fr':'French','fy':'Western Frisian','ff':'Fulah','Ga':'Georgian','gd':'Gaelic; Scottish Gaelic','ga':'Irish',
'gl':'Galician','gv':'Manx','el':'Greek-Modern (1453-)','gn':'Guarani','gu':'Gujarati','ht':'Haitian; Haitian Creole','ha':'Hausa',
'he':'Hebrew','hz':'Herero','hi':'Hindi','ho':'Hiri Motu','hr':'Croatian','hu':'Hungarian','hy':'Armenian','ig':'Igbo','is':'Icelandic',
'io':'Ido','ii':'Sichuan Yi; Nuosu','iu':'Inuktitut','ie':'Interlingue; Occidental',
'ia':'Interlingua (International Auxiliary Language Association)','id':'Indonesian','ik':'Inupiaq','is':'Icelandic','it':'Italian',
'jv':'Javanese','ja':'Japanese','kl':'Kalaallisut; Greenlandic','kn':'Kannada','ks':'Kashmiri','ka':'Georgian','kr':'Kanuri','kk':'Kazakh',
'km':'Central Khmer','ki':'Kikuyu; Gikuyu','rw':'Kinyarwanda','ky':'Kirghiz; Kyrgyz','kv':'Komi','kg':'Kongo','ko':'Korean',
'kj':'Kuanyama; Kwanyama','ku':'Kurdish','lo':'Lao','la':'Latin','lv':'Latvian','li':'Limburgan; Limburger; Limburgish','ln':'Lingala',
'lt':'Lithuanian','lb':'Luxembourgish; Letzeburgesch','lu':'Luba-Katanga','lg':'Ganda','mk':'Macedonian','mh':'Marshallese',
'ml':'Malayalam','mi':'Maori','mr':'Marathi','ms':'Malay','Mi':'Micmac','mk':'Macedonian','mg':'Malagasy','mt':'Maltese',
'mn':'Mongolian','mi':'Maori','ms':'Malay','my':'Burmese','na':'Nauru','nv':'Navajo; Navaho','nr':'Ndebele-South; South Ndebele',
'nd':'Ndebele-North; North Ndebele','ng':'Ndonga','ne':'Nepali','nl':'Dutch; Flemish','nn':'Norwegian Nynorsk; Nynorsk:Norwegian',
'nb':'Bokmål-Norwegian; Norwegian Bokmål','no':'Norwegian','oc':'Occitan (post 1500)','oj':'Ojibwa','or':'Oriya','om':'Oromo',
'os':'Ossetian; Ossetic','pa':'Panjabi; Punjabi','fa':'Persian','pi':'Pali','pl':'Polish','pt':'Portuguese','ps':'Pushto; Pashto',
'qu':'Quechua','rm':'Romansh','ro':'Romanian; Moldavian; Moldovan','rn':'Rundi','ru':'Russian','sg':'Sango','sa':'Sanskrit',
'si':'Sinhala; Sinhalese','sk':'Slovak','sk':'Slovak','sl':'Slovenian','se':'Northern Sami','sm':'Samoan','sn':'Shona','sd':'Sindhi',
'so':'Somali','st':'Sotho-Southern','es':'Spanish','sq':'Albanian','sc':'Sardinian','sr':'Serbian','ss':'Swati',
'su':'Sundanese','sw':'Swahili','sv':'Swedish','ty':'Tahitian','ta':'Tamil','tt':'Tatar','te':'Telugu','tg':'Tajik','tl':'Tagalog',
'th':'Thai','bo':'Tibetan','ti':'Tigrinya','to':'Tonga (Tonga Islands)','tn':'Tswana','ts':'Tsonga','tk':'Turkmen','tr':'Turkish',
'tw':'Twi','ug':'Uighur; Uyghur','uk':'Ukrainian','ur':'Urdu','uz':'Uzbek','ve':'Venda','vi':'Vietnamese','vo':'Volapük','cy':'Welsh',
'wa':'Walloon','wo':'Wolof','xh':'Xhosa','yi':'Yiddish','yo':'Yoruba','za':'Zhuang; Chuang','zh':'Chinese','zu':'Zulu'}

languageNameList = ['Afar', 'Abkhazian', 'Afrikaans', 'Akan', 'Albanian', 'Amharic', 'Arabic', 'Aragonese', 'Armenian', 'Assamese', 'Avaric', 'Avestan', 'Aymara', 'Azerbaijani', 'Bashkir', 'Bambara', 'Basque', 'Belarusian', 'Bengali', 'Bihari languages', 'Bislama', 'Tibetan', 'Bosnian', 'Breton', 'Bulgarian', 'Burmese', 'Catalan', 'Valencian', 'Czech', 'Chamorro', 'Chechen', 'Chinese', 'Church Slavic', 'Old Slavonic', 'Church Slavonic', 'Old Bulgarian', 'Old Church Slavonic', 'Chuvash', 'Cornish', 'Corsican', 'Cree', 'Welsh', 'Danish', 'German', 'Divehi', 'Dhivehi', 'Maldivian', 'Dutch', 'Flemish', 'Dzongkha', 'Greek-Modern (1453-)', 'English', 'Esperanto', 'Estonian', 'Ewe', 'Faroese', 'Persian', 'Fijian', 'Finnish', 'French', 'Western Frisian', 'Fulah', 'Georgian', 'Gaelic', 'Scottish Gaelic', 'Irish', 'Galician', 'Manx', 'Guarani', 'Gujarati', 'Haitian', 'Haitian Creole', 'Hausa', 'Hebrew', 'Herero', 'Hindi', 'Hiri Motu', 'Croatian', 'Hungarian', 'Igbo', 'Icelandic', 'Ido', 'Sichuan Yi', 'Nuosu', 'Inuktitut', 'Interlingue', 'Occidental', 'Interlingua (International Auxiliary Language Association)', 'Indonesian', 'Inupiaq', 'Italian', 'Javanese', 'Japanese', 'Kalaallisut', 'Greenlandic', 'Kannada', 'Kashmiri', 'Georgian', 'Kanuri', 'Kazakh', 'Central Khmer', 'Kikuyu', 'Gikuyu', 'Kinyarwanda', 'Kirghiz', 'Kyrgyz', 'Komi', 'Kongo', 'Korean', 'Kuanyama', 'Kwanyama', 'Kurdish', 'Lao', 'Latin', 'Latvian', 'Limburgan', 'Limburger', 'Limburgish', 'Lingala', 'Lithuanian', 'Luxembourgish', 'Letzeburgesch', 'Luba-Katanga', 'Ganda', 'Macedonian', 'Marshallese', 'Malayalam', 'Maori', 'Marathi', 'Malay', 'Micmac', 'Malagasy', 'Maltese', 'Mongolian', 'Nauru', 'Navajo', 'Navaho', 'Ndebele-South', 'South Ndebele', 'Ndebele-North', 'North Ndebele', 'Ndonga', 'Nepali', 'Norwegian Nynorsk', 'Nynorsk:Norwegian', 'Bokmål-Norwegian', 'Norwegian Bokmål', 'Norwegian', 'Occitan (post 1500)', 'Ojibwa', 'Oriya', 'Oromo', 'Ossetian', 'Ossetic', 'Panjabi', 'Punjabi', 'Pali', 'Polish', 'Portuguese', 'Pushto', 'Pashto', 'Quechua', 'Romansh', 'Romanian', 'Moldavian', 'Moldovan', 'Rundi', 'Russian', 'Sango', 'Sanskrit', 'Sinhala', 'Sinhalese', 'Slovak', 'Slovenian', 'Northern Sami', 'Samoan', 'Shona', 'Sindhi', 'Somali', 'Sotho-Southern', 'Spanish', 'Sardinian', 'Serbian', 'Swati', 'Sundanese', 'Swahili', 'Swedish', 'Tahitian', 'Tamil', 'Tatar', 'Telugu', 'Tajik', 'Tagalog', 'Thai', 'Tigrinya', 'Tonga (Tonga Islands)', 'Tswana', 'Tsonga', 'Turkmen', 'Turkish', 'Twi', 'Uighur', 'Uyghur', 'Ukrainian', 'Urdu', 'Uzbek', 'Venda', 'Vietnamese', 'Volapük', 'Walloon', 'Wolof', 'Xhosa', 'Yiddish', 'Yoruba', 'Zhuang', 'Chuang', 'Zulu']
languageFullNameDict = {'Afar': 'aa',
 'Abkhazian': 'ab',
 'Afrikaans': 'af',
 'Akan': 'ak',
 'Albanian': 'sq',
 'Amharic': 'am',
 'Arabic': 'ar',
 'Aragonese': 'an',
 'Armenian': 'hy',
 'Assamese': 'as',
 'Avaric': 'av',
 'Avestan': 'ae',
 'Aymara': 'ay',
 'Azerbaijani': 'az',
 'Bashkir': 'ba',
 'Bambara': 'bm',
 'Basque': 'eu',
 'Belarusian': 'be',
 'Bengali': 'bn',
 'Bihari languages': 'bh',
 'Bislama': 'bi',
 'Tibetan': 'bo',
 'Bosnian': 'bs',
 'Breton': 'br',
 'Bulgarian': 'bg',
 'Burmese': 'my',
 'Catalan': 'ca',
 'Valencian': 'ca',
 'Czech': 'cs',
 'Chamorro': 'ch',
 'Chechen': 'ce',
 'Chinese': 'zh',
 'Church Slavic': 'cu',
 'Old Slavonic': 'cu',
 'Church Slavonic': 'cu',
 'Old Bulgarian': 'cu',
 'Old Church Slavonic': 'cu',
 'Chuvash': 'cv',
 'Cornish': 'kw',
 'Corsican': 'co',
 'Cree': 'cr',
 'Welsh': 'cy',
 'Danish': 'da',
 'German': 'de',
 'Divehi': 'dv',
 'Dhivehi': 'dv',
 'Maldivian': 'dv',
 'Dutch': 'nl',
 'Flemish': 'nl',
 'Dzongkha': 'dz',
 'Greek-Modern (1453-)': 'el',
 'English': 'en',
 'Esperanto': 'eo',
 'Estonian': 'et',
 'Ewe': 'ee',
 'Faroese': 'fo',
 'Persian': 'fa',
 'Fijian': 'fj',
 'Finnish': 'fi',
 'French': 'fr',
 'Western Frisian': 'fy',
 'Fulah': 'ff',
 'Georgian': 'ka',
 'Gaelic': 'gd',
 'Scottish Gaelic': 'gd',
 'Irish': 'ga',
 'Galician': 'gl',
 'Manx': 'gv',
 'Guarani': 'gn',
 'Gujarati': 'gu',
 'Haitian': 'ht',
 'Haitian Creole': 'ht',
 'Hausa': 'ha',
 'Hebrew': 'he',
 'Herero': 'hz',
 'Hindi': 'hi',
 'Hiri Motu': 'ho',
 'Croatian': 'hr',
 'Hungarian': 'hu',
 'Igbo': 'ig',
 'Icelandic': 'is',
 'Ido': 'io',
 'Sichuan Yi': 'ii',
 'Nuosu': 'ii',
 'Inuktitut': 'iu',
 'Interlingue': 'ie',
 'Occidental': 'ie',
 'Interlingua (International Auxiliary Language Association)': 'ia',
 'Indonesian': 'id',
 'Inupiaq': 'ik',
 'Italian': 'it',
 'Javanese': 'jv',
 'Japanese': 'ja',
 'Kalaallisut': 'kl',
 'Greenlandic': 'kl',
 'Kannada': 'kn',
 'Kashmiri': 'ks',
 'Kanuri': 'kr',
 'Kazakh': 'kk',
 'Central Khmer': 'km',
 'Kikuyu': 'ki',
 'Gikuyu': 'ki',
 'Kinyarwanda': 'rw',
 'Kirghiz': 'ky',
 'Kyrgyz': 'ky',
 'Komi': 'kv',
 'Kongo': 'kg',
 'Korean': 'ko',
 'Kuanyama': 'kj',
 'Kwanyama': 'kj',
 'Kurdish': 'ku',
 'Lao': 'lo',
 'Latin': 'la',
 'Latvian': 'lv',
 'Limburgan': 'li',
 'Limburger': 'li',
 'Limburgish': 'li',
 'Lingala': 'ln',
 'Lithuanian': 'lt',
 'Luxembourgish': 'lb',
 'Letzeburgesch': 'lb',
 'Luba-Katanga': 'lu',
 'Ganda': 'lg',
 'Macedonian': 'mk',
 'Marshallese': 'mh',
 'Malayalam': 'ml',
 'Maori': 'mi',
 'Marathi': 'mr',
 'Malay': 'ms',
 'Micmac': 'Mi',
 'Malagasy': 'mg',
 'Maltese': 'mt',
 'Mongolian': 'mn',
 'Nauru': 'na',
 'Navajo': 'nv',
 'Navaho': 'nv',
 'Ndebele-South': 'nr',
 'South Ndebele': 'nr',
 'Ndebele-North': 'nd',
 'North Ndebele': 'nd',
 'Ndonga': 'ng',
 'Nepali': 'ne',
 'Norwegian Nynorsk': 'nn',
 'Nynorsk:Norwegian': 'nn',
 'Bokmål-Norwegian': 'nb',
 'Norwegian Bokmål': 'nb',
 'Norwegian': 'no',
 'Occitan (post 1500)': 'oc',
 'Ojibwa': 'oj',
 'Oriya': 'or',
 'Oromo': 'om',
 'Ossetian': 'os',
 'Ossetic': 'os',
 'Panjabi': 'pa',
 'Punjabi': 'pa',
 'Pali': 'pi',
 'Polish': 'pl',
 'Portuguese': 'pt',
 'Pushto': 'ps',
 'Pashto': 'ps',
 'Quechua': 'qu',
 'Romansh': 'rm',
 'Romanian': 'ro',
 'Moldavian': 'ro',
 'Moldovan': 'ro',
 'Rundi': 'rn',
 'Russian': 'ru',
 'Sango': 'sg',
 'Sanskrit': 'sa',
 'Sinhala': 'si',
 'Sinhalese': 'si',
 'Slovak': 'sk',
 'Slovenian': 'sl',
 'Northern Sami': 'se',
 'Samoan': 'sm',
 'Shona': 'sn',
 'Sindhi': 'sd',
 'Somali': 'so',
 'Sotho-Southern': 'st',
 'Spanish': 'es',
 'Sardinian': 'sc',
 'Serbian': 'sr',
 'Swati': 'ss',
 'Sundanese': 'su',
 'Swahili': 'sw',
 'Swedish': 'sv',
 'Tahitian': 'ty',
 'Tamil': 'ta',
 'Tatar': 'tt',
 'Telugu': 'te',
 'Tajik': 'tg',
 'Tagalog': 'tl',
 'Thai': 'th',
 'Tigrinya': 'ti',
 'Tonga (Tonga Islands)': 'to',
 'Tswana': 'tn',
 'Tsonga': 'ts',
 'Turkmen': 'tk',
 'Turkish': 'tr',
 'Twi': 'tw',
 'Uighur': 'ug',
 'Uyghur': 'ug',
 'Ukrainian': 'uk',
 'Urdu': 'ur',
 'Uzbek': 'uz',
 'Venda': 've',
 'Vietnamese': 'vi',
 'Volapük': 'vo',
 'Walloon': 'wa',
 'Wolof': 'wo',
 'Xhosa': 'xh',
 'Yiddish': 'yi',
 'Yoruba': 'yo',
 'Zhuang': 'za',
 'Chuang': 'za',
 'Zulu': 'zu'}

def findLanguageShortCode(lang):
    potentialMatches=difflib.get_close_matches(lang,languageNameList,1,0.1)
    print(potentialMatches)
    return languageFullNameDict[potentialMatches[0]]
    val = int(input(""))
    if val == 1:
        return languageFullNameDict[potentialMatches[0]]
    else:
            for n in range(len(potentialMatches)):
                print("Press "+ str(n+1) + " if you want to translate the text to " + potentialMatches[n])
            print("Press 0 to cancel translation")
            val = int(input(""))
            while (val < 0 or val > len(potentialMatches)):
                val = int(input(""))
            if val == 0:
                return
            else:
                return languageFullNameDict[potentialMatches[val-1]]